### PR TITLE
CI Update

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### HTTPS Corrected URLs 
Was | Now 
--- | --- 
http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-introduction-to-algorithms-sma-5503-fall-2005/ | https://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-046j-introduction-to-algorithms-sma-5503-fall-2005/ 
http://www.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693 | https://www.amazon.com/Algorithm-Design-Manual-Steven-Skiena/dp/1848000693 
http://www.amazon.com/Algorithms-4th-Robert-Sedgewick/dp/032157351X | https://www.amazon.com/Algorithms-4th-Robert-Sedgewick/dp/032157351X 
http://www.amazon.com/Computational-Geometry-Applications-Mark-Berg/dp/3540779736 | https://www.amazon.com/Computational-Geometry-Applications-Mark-Berg/dp/3540779736 
http://www.amazon.com/Concrete-Mathematics-Foundation-Computer-Science/dp/0201558025 | https://www.amazon.com/Concrete-Mathematics-Foundation-Computer-Science/dp/0201558025 
http://www.amazon.com/Discrete-Mathematics-Applications-Kenneth-Rosen/dp/0072899050 | https://www.amazon.com/Discrete-Mathematics-Applications-Kenneth-Rosen/dp/0072899050 
http://www.amazon.com/How-Solve-It-Mathematical-Princeton/dp/069111966X | https://www.amazon.com/How-Solve-It-Mathematical-Princeton/dp/069111966X 
http://www.amazon.com/Linear-Algebra-Its-Applications-5th/dp/032198238X/ref=sr_1_1?ie=UTF8&qid=1455475253&sr=8-1&keywords=Linear+Algebra+and+Its+Applications | https://www.amazon.com/Linear-Algebra-Its-Applications-5th/dp/032198238X/ref=sr_1_1?ie=UTF8&qid=1455475253&sr=8-1&keywords=Linear+Algebra+and+Its+Applications 
http://www.amazon.com/Programming-Challenges-Contest-Training-Computer/dp/0387001638 | https://www.amazon.com/Programming-Challenges-Contest-Training-Computer/dp/0387001638 

### Other Corrected URLs 
Was | Now 
--- | --- 
https://www.hackerearth.com/codemonk/ | https://www.hackerearth.com/practice/codemonk/ 
https://www.hackerearth.com/notes/trending/ | https://www.hackerearth.com/practice/notes/trending/

### CODE REVIEW

**Comment by ReadmeCritic** [comment]
http://clist.by/ is down at the moment
Consider removing if issue persists

**Comment by lnishan** [comment]
@ReadmeCritic @dkhamsing

Thanks :)
I feel like I need to give you some credits somewhere in README for these amazing work.

- clist.by
This site has poor uptimes. It's a known issue (also the case with A2OJ).

**Comment by babhishek21** [comment]
@lnishan I don't know if Awesome Lists need to follow certain standards/rules. You could always make a Wiki for this repository and list contributors and Contributing guides there. That way you only have to mention the wiki instead of bloating the main README.

**Comment by lnishan** [comment]
@babhishek21 
Yes, there are some loosely-defined rules (see [The awesome manifesto](https://github.com/sindresorhus/awesome/blob/master/awesome.md)).

I think that's a great idea.
We're getting more and more contributors lately (which is fantastic), and the list only gets bigger.

**Pull request merged**
