### PR TITLE
Added COJ (coj.uci.cu) to ###Sites to Practice

### PR DESCRIPTION
**Pull request by frarteaga**
More info about COJ: 
- https://ciiwiki.ecs.baylor.edu/index.php/Caribbean_Online_Judge_%28COJ%29
- http://coj.uci.cu/general/about.xhtml
- http://coj.uci.cu/general/docs.xhtml
- http://coj.uci.cu/general/faqs.xhtml

### CODE REVIEW

**Comment by lnishan** [comment]
I'll review this later as I'm currently at work.

In the mean time, how would you recommend COJ? (Why is it a good OJ?)

I'm less familiar with Latin American Regions, but I think I've heard of COJ.

**Comment by frarteaga** [comment]
Hi

COJ has been in operation for over 6 years, support partial evaluation in 24 hour archive with more than 2700 taged problems and ~400 open contests. It support [Progressive Contest Style](http://coj.uci.cu/contest/contestview.xhtml?cid=1494), [here](http://coj.uci.cu/contest/cscoreboard.xhtml?cid=1494) an example running now.

**Comment by lnishan** [comment]
Thanks :)

I'll take a closer look at the site when I get off work today.

**Comment by lenovo321** [comment]
More arguments:

There are a few online judges in Latin American Region, and COJ is the most important of them in terms of registered_users/registered_countries/archives_of_problems/hosted_competitions/etc. From our opinion is the only one which implement the [Progressive Contest Style](http://coj.uci.cu/contest/contestview.xhtml?cid=1494) as Frank previously mention.

Also, COJ currently have modules which make it a not-ordinary online judge, such that an automatic (algorithmic based) module for problems recommendation. The problems are classified by topics and complexity. Also COJ has a notable statistic data representation with graphics (bars, time-line, spider-graph, etc.) and others. COJ has a Web Service API, one App for Android (APK), support for Virtual Contest, a integrated Forum using phpBB, one MicroBlog, and others [tools](http://coj.uci.cu/general/tools.xhtml).

Greetings.

**Comment by lnishan** [comment]
That sounds super cool.

Thanks @lenovo321 !

**Comment by lnishan** [comment]
Looks nice.
Merged :)
Thank you! (Sorry for the wait)

**Pull request merged**
