### PR TITLE
added cses.fi to syllabuses and lynbrookcs

### PR DESCRIPTION
**Pull request by Divide-By-0**

### CODE REVIEW

**Comment by lnishan** [comment]
Hello,
Thanks for the PR.

The book is amazing. It's definitely one of the best books on competitive programming.
(I've really been absent from the scene way too long!)

For the second resource however, I'm sorry but I don't see where the slides are at Lynbrook CS?

**Comment by lnishan** [comment]
and there's a section for books.

**Comment by Divide-By-0** [comment]
OK, I can repush without the book; the older posts in Lynbrook CS have links to slides if you click the boxes, the rest should be uploaded shortly.

**Comment by lnishan** [comment]
I mean the book is in the wrong section.

As for Lynbrook CS, I don't see a reason to include it.

**Comment by Divide-By-0** [comment]
OK, I undid my first edit and put two other resources from my bookmarks. Haven't done competitive programming in a while either, just wanted to share what I had :)

**Comment by lnishan** [comment]
For the UIUC course, it is awesome. Thanks for sharing.
It is however also in the wrong section (should be in the one with courses for algorithms and data structures).

For the free algorithm book, it is a serious violation of copyrights.

**Comment by Divide-By-0** [comment]
alright, removed the books link and fixed class location.

**Pull request merged**
