### PR TITLE
Remove BNU Online Judge

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Site has been removed http://www.bnuoj.com/v3/

### CODE REVIEW

**Comment by lnishan** [comment]
image

BNU Judge is up for me.
Where are you from? There might be issues on the ISP end (Server location seems to be China).

**Comment by imcaffrey** [comment]
@ReadmeCritic 
www.bnuoj.com was not available for the past few hours, it's back now.
There is also another domain: acm.bnu.edu.cn

**Comment by lnishan** [comment]
@imcaffrey Thanks for the info! :+1:

**Comment by ReadmeCritic** [comment]
Ok

**Comment by lnishan** [comment]
@ReadmeCritic 
Btw, thanks for helping! : D
Highly appreciated.

**Pull request closed without merging**
