### PR TITLE
Add a proposed competitive programming site on Stack Exchange

### PR DESCRIPTION
**Pull request by RedGreenCode**
The [Competitive Programming topic on Quora](https://www.quora.com/topic/Competitive-Programming) is a popular destination for CP questions. However, Quora's moderation philosophy makes it difficult to maintain content quality. Stack Exchange has a history of strict quality controls. It would be useful for the competitive programming community to weigh in on whether such an alternative site is worthwhile.

### CODE REVIEW

**Comment by lnishan** [comment]
I had a look at the proposal, and I completely agree with your statements and reasonings.
Quora does lack quality control and Codeforces isn't necessarily the best place to ask questions.

I'll get back to this later :)
I think I'm okay with having this on the list.

**Comment by lnishan** [comment]
I'll merge it for now.

Please notify me should the proposal gets rejected (Have to remove it unfortunately if that happens).

**Comment by cristaloleg** [comment]
Also check this one [compsci.stackexchange](https://cs.stackexchange.com)

**Comment by lnishan** [comment]
I think this sub (Computer Science) is too broad :/

There are some questions about algorithms though.

**Comment by RedGreenCode** [comment]
Stack Exchange sites are good for general questions about algorithms and coding. But if a question gets too specific to competitive programming (e.g., mentioning an online judge or a problem), it tends to attract negative attention.

**Pull request merged**
