### PR TITLE
Adding channel: Arabic Competive Programming

### PR DESCRIPTION
**Pull request by mostafa-saad**
My channel covers wide variety of algorithms for Arabian speakers. However, all text is in English.

### CODE REVIEW

**Comment by lnishan** [comment]
Hello @mostafa-saad 
Thanks for the PR :)
I also read your comment on Codeforces earlier.

I know your channel!
I came across your channel a while ago actually (while learning something I couldn't remember).
It wasn't in my bookmarks because I don't understand Arabic, 
but it looks good to me - This list is for aspiring competitive programmers worldwide :)

**Comment by mostafa-saad** [comment]
Cool :)

**Comment by babhishek21** [comment]
@mostafa-saad I think your Github [repo accompanying the videos](https://github.com/mostafa-saad/ArabicCompetitiveProgramming) is even more useful in this context. The videos are not in English, but the slides are. They are available in the repository I believe. 

Additionally, I really liked your Junior Training Sheet V2. The sheet is located [here](https://docs.google.com/spreadsheets/d/1iJZWP2nS_OB3kCTjq8L6TrJJ4o-5lhxDOyTaocSYc-k/).

I think including them as well would be really useful.

**Comment by mostafa-saad** [comment]
@babhishek21 
Great...see whereever to add, and add them. Or I can do that and make a pull request.

**Comment by babhishek21** [comment]
@mostafa-saad Feel free to make a pull request. :smile:

**Comment by lnishan** [comment]
Oh wow! 

I'll do it eventually if you're all busy :)
Pretty amazing stuff you have there.

**Comment by mostafa-saad** [comment]
Hi,

I just created the pull request...feel free to edit in whatever suitable style

**Pull request merged**
