### PR TITLE
add Uri Online Judge

### PR DESCRIPTION
**Pull request by dreamtocode**
It's good site for beginners but there is more than that... I did the challenge last year and it turned out interesting tbh.

### CODE REVIEW

**Comment by lnishan** [comment]
Hello,  
I had a quick look. It looks good indeed.  
However I believe I recognised some problems from UVa online judge.  
Are you aware of where does URI online judge get its problems?

**Comment by dreamtocode** [comment]
Hello,

I'm not aware of it. 

Can you be more specific about the problems ?

**Comment by lnishan** [comment]
Well It doesn't seem to be discussed as often compared to the ones on the list.  
In addition, I cannot verify the "awsomeness" of it (a quick search on Codeforces showed up nothing but heavily downvoted posts - even though it's attributed to the terrible grammar and formatting).

I'm also slightly concerned about the problems not being very original (In that case, people can just goto the source platform to practice).

**Comment by dreamtocode** [comment]
Most of them is easy and that's why probable.

Yes I can verify that some of their problems has got terrible grammar because some of them I reported last year. 

Things that I like about UOJ - their problems are separated by topic author and it's divided in levels.

I agree that other sites are more popular and they got more problems too.

**Comment by dreamtocode** [comment]
All that was discussed above says that you don't have to add that URI online judge.
So I'll close this pr.

**Comment by lnishan** [comment]
I would just need someone else to back it.  
It does seem like a good platform, but I have no knowledge of it personally.

When I mentioned terrible grammar earlier, I wasn't referring to the problem statements, but the posts on Codeforces that refer to the URI judge. I cannot really get any information on those posts.  
I'll try to find out more about it later.

Thank you for the PR :)

**Comment by dreamtocode** [comment]
I got it. Now I see what you mean. 

That's really good platform but still they had lot's of things to improve.

Ok try it later... Don't forget to check out their toolkit, that's one of the greatest thing about their platform.

Welcome !

**Pull request closed without merging**
