### PR TITLE
Add site to online judges list

### PR DESCRIPTION
**Pull request by ThiagoInocencio**
Hi, could you add the URI Online Judge to the list of Sites to Practice?

A little bit about URI: The URI Online Judge is a project that is being developed by the Computer Science Department of URI University. The main goal of the project is to provide programming practice and knowledge sharing.

url: https://www.urionlinejudge.com.br

All the best,

### CODE REVIEW

**Comment by lnishan** [comment]
Thanks for the PR.

Someone actually suggested URI online judge right when this list was initially created.
I was unsure about its problem archive which seems to have many taken from UVa online judge.
On a closer look I didn't think it should be added. It's just a little below the caliber of other ones on the list.

On a side note, you made changes to the wrong branch.
The `cf` branch is for adding CF-specific markdown syntax for usernames.

**Comment by lnishan** [comment]
Umm and, you didn't seem to have made any changes.

Make sure you understand what a `Pull Request` is.

**Comment by ThiagoInocencio** [comment]
Humm... I agree with your opinion, but I think URI has a better user interface than the other ones. Yes I know, beautiful interface is not a good argument to decide which is better than another.
thank u.

**Comment by lnishan** [comment]
@ThiagoInocencio 
Yes, I agree.
It does have a better interface than those old-school online judges.
It really kept me thinking a lot before I decided not to include it.

Anyways,
Thanks for contributing :)

**Pull request closed without merging**
