### PR TITLE
Added Codechef's Indian Programming Camp Lectures

### PR DESCRIPTION
**Pull request by babhishek21**
Added video playlist of lectures from Codechef's Indian Programming Camp 2016. I think it is a great resource to bridge the gap between an intermediate and advanced competitive programmer. 

Additionally fixed a typo in Contributing Guidelines Readme.

### CODE REVIEW

**Comment by lnishan** [comment]
I've add the resource.

Thanks! :D

**Comment by babhishek21** [comment]
Great! Umm.. this is just for your information and knowledge, but you should really try using GitHub's workflow model when dealing with a public project that has lots of contributors. Case in point, is this Pull Request.

What you did:
+ You saw the incoming changes. You found them alright, but you wanted to make some modifications. So you applied the entire modified changes yourself.
+ This is pure duplication of effort. Had this been a repository of say, a thousand lines of code, this kind of workflow gives births to mistakes, since you are trying to translate a fellow contributor's subtle touches to your own style.
+ You closed the PR without accepting changes and yet did not delete the branch. Code pollution occurred in the fork.

What you should have done:
+ Let the contributor know that some modifications might be required. This is basic peer-driven code review. Once the contributor makes the resulting modifications and the peer-review passes, **_accept_** the PR and merge the changes.  

**_OR_**  

+ Merge in the changes in the PR as is. Later apply your own modifications on top of that. Additionally, for posterity, let the contributors know what little modifications you did and why.

==

+ Additionally, delete the branch if you do not expect any more changes coming in from it.

**Comment by lnishan** [comment]
Okay well umm. Let me explain.

The reason is "efficiency".

In PR #25 , I did exactly what you said.
In this PR, the short answer is that there are issues which I cannot just add more commits to it.
Commenting back and forth on a single line or two isn't something I want to do.

1. Wrong section. This is not a course for algorithms and data structures, but for competitive programming. This is why I didn't add commits on top of yours.
2. The PR is for adding Indian Programming Camp into the list, but you added unrelated modifications (What if I want just the item alone?). You should create a second PR for this. It's also weird for me to add commits to remove the modifications you made to `CONTRIBUTING.md`.
3. Typo. focu"ss"ed.
4. 3-star rating is a little biased. This might be another long conversation.

**Comment by babhishek21** [comment]
1. and 4. I'll leave it to your better judgement. I would not have contested those.
2. and 3. Well sometimes, very small changes (like typos) do not require peer review. I would apply your efficiency argument in this case for not doing a separate PR. We have cherry picking in `git` for cases like this when you want ony part of the changes. That's why I made a separate commit for the typo.

**Comment by lnishan** [comment]
Oh you're right!

I totally forgot about cherrypick.
But doesn't that also pollute the commit history?

I think It would be great if GitHub allows us to do that with web interface.

**Comment by babhishek21** [comment]
>I totally forgot about cherrypick.
But doesn't that also pollute the commit history?

It would, temporarily. And only to my fork. Once the changes are merged, I would pull in changes from your repo as an upstream and then remove the irrelevant commits from my fork. So win-win.

**Pull request closed without merging**
