### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dzarrr**
Add FAQ about how does Competitive Programming help people to get a job.

### CODE REVIEW

**Comment by lnishan** [comment]
Hello,
Thanks for the PR.

Can you check on the changes you made?
You can do so by clicking on the "Files changed" tab (or [https://github.com/lnishan/awesome-competitive-programming/pull/30/files](https://github.com/lnishan/awesome-competitive-programming/pull/30/files))
In short, you inserted an extra line and broke the table syntax.

**Comment by dzarrr** [comment]
I am truly sorry if I messed up the README file.  Actually,  I just started
learning Github and want to try a few things.  Please ignore the change I
had made.

Thank you

**Comment by lnishan** [comment]
Never feel sorry for that :)

Feel free to try again (delete your fork and create a new PR).
There's always a first for everything!

**Comment by dzarrr** [comment]
Thank you very much for the kind words :)

**Comment by lnishan** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
